package br.com.nora.api.application.ports;

import java.util.List;
import java.util.UUID;

/** Persistence of meeting embeddings (RAG). Scoped by tenant (RLS, ADR 0028). */
public interface EmbeddingRepository {

    /** Inserts/updates the embedding of a meeting. */
    void upsert(UUID meetingId, UUID tenantId, String modelId, float[] vector, int sourceChars);

    /** All tenant embeddings generated by the same {@code modelId} (same vector space). */
    List<StoredEmbedding> findByTenantAndModel(UUID tenantId, String modelId);

    /**
     * Backfill candidates of one tenant: meetings that already carry an analysed summary but whose
     * vector is missing or was produced by a different model. Newest first, and capped by the
     * limit, because the caller pays the provider once per row returned.
     */
    List<PendingIndex> findPendingIndex(UUID tenantId, String modelId, int limit);

    /** How many rows {@link #findPendingIndex} would return with no limit. */
    long countPendingIndex(UUID tenantId, String modelId);

    record StoredEmbedding(UUID meetingId, float[] vector) {}

    /**
     * One backfill candidate. {@code text} is the persisted summary snippet — the same PII-safe
     * input the live indexing path uses, never the raw transcript (ADR 0012).
     */
    record PendingIndex(UUID meetingId, String text) {}
}
