package br.com.nora.api.application.ports;

import java.util.List;
import java.util.UUID;

/** Persistence of meeting embeddings (RAG). Scoped by tenant (RLS, ADR 0028). */
public interface EmbeddingRepository {

    /** Inserts/updates the embedding of a meeting. */
    void upsert(UUID meetingId, UUID tenantId, String modelId, float[] vector, int sourceChars);

    /** All tenant embeddings generated by the same {@code modelId} (same vector space). */
    List<StoredEmbedding> findByTenantAndModel(UUID tenantId, String modelId);

    record StoredEmbedding(UUID meetingId, float[] vector) {}
}
