package br.com.nora.api.application.ports;

import br.com.nora.api.domain.analysis.MeetingAnalysis;
import java.util.Collection;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/** Persistence of the analysis generated by the NLP worker. Always scoped by tenant. */
public interface MeetingAnalysisRepository {

    MeetingAnalysis save(MeetingAnalysis analysis);

    Optional<MeetingAnalysis> findByMeetingId(UUID meetingId, UUID tenantId);

    /** Deletes the meeting's existing analysis (idempotent). Useful for reprocessing. */
    void deleteByMeetingId(UUID meetingId, UUID tenantId);

    /**
     * Aggregated counts per meeting, in ONE query (without materializing the collections). To
     * enrich the listing without N+1.
     */
    List<AnalysisCounts> countsByMeetingIds(Collection<UUID> meetingIds, UUID tenantId);

    /** Counts of an analysis for the listing row. */
    record AnalysisCounts(UUID meetingId, int actionItems, int risks, int opportunities) {}
}
