#!/usr/bin/env bash
#
# offsite-backup.sh — copies the verified database dumps OFF this machine.
#
# WHY THIS EXISTS
# ---------------
# `../backup/run-backup.sh` produces a good backup and puts it in the wrong place. Its own
# header says so, in capitals: "A BACKUP ON THE SAME HOST IS NOT A BACKUP". The dumps land in
# ${BACKUP_DIR:-/srv/nora/backups}, which on the default layout is the same filesystem as the
# Postgres volume, and nothing moved them anywhere else. Losing the host lost the database,
# every dump of it, the age private key and the secrets file in one event — and the documented
# mitigation (rclone/rsync) was named as "not done today" in two places rather than written.
# This is that leg.
#
# WHY IT RUNS ON THE HOST AND NOT IN THE `backup` CONTAINER
# ---------------------------------------------------------
# It cannot run there. The `backup` service sits on the `data` bridge, which is
# `internal: true` — no route to the internet — and its image (postgres:16-alpine) carries
# neither rclone nor rsync nor ssh. Giving that container egress to reach an off-host target
# would put an internet-facing path on the network segment whose entire purpose is not having
# one. The host already has egress, already has root, and already reads /srv/nora/backups.
#
# WHAT IT COPIES, AND WHAT IT DELIBERATELY DOES NOT
# -------------------------------------------------
# COPIES: the newest verified `.dump` of each database, plus its `.sha256` and `.toc`. Only
# files that already carry the `.dump` name, which by construction means `pg_restore --list`
# accepted them (run-backup.sh promotes `.part` -> `.dump` only after that check). An
# unverified file is not worth the bandwidth and is actively harmful off-site, where it looks
# like a backup.
#
# DOES NOT COPY, and this is a decision rather than an omission:
#   prometheus_data (30d of metrics) and loki_data (30d of logs) — derived telemetry. It is
#   regenerated by the stack coming back up, and the cost of not having it is real but bounded
#   and worth naming: after an incident that takes the host, the forensic record OF that
#   incident goes with it. Copying them would mean shipping tens of gigabytes of
#   append-heavy data hourly to protect evidence about an event that already happened, which
#   is the wrong trade against tenant data that cannot be reproduced from anything.
#   grafana_data — nothing in it is a source of truth. Dashboards and datasources are
#   provisioned from this repository (observability/grafana/provisioning/), and everything
#   else in that volume is UI state.
#   caddy_data / caddy_config — ACME state for certificates the origin does not use; TLS is
#   terminated at Cloudflare. Reissued automatically if it ever mattered.
#   The age key and the secrets file — deliberately NOT here. They are the other half of the
#   disaster story and belong in the operator's own vault, off any machine this script can
#   reach; ADR 0036 §4 has the argument. A backup destination holding both the ciphertext and
#   the key that opens it is one credential away from being the breach.
#
# CONFIGURATION — one variable, and the script refuses to guess
# -------------------------------------------------------------
#   NORA_OFFSITE_TARGET   (REQUIRED) where the copies go. Three accepted forms:
#
#       rclone:<remote>:<path>     e.g. rclone:b2-nora:nora/db
#                                  Any rclone backend the operator has configured in
#                                  /root/.config/rclone/rclone.conf. This is the recommended
#                                  form: object storage is off-site in the sense that matters
#                                  (different failure domain, not just a different disk).
#
#       rsync:<destination>        e.g. rsync:backups@nas.lan:/volume1/nora
#                                  Anything `rsync -e ssh` accepts. Needs a key in
#                                  /root/.ssh able to reach it non-interactively.
#
#       none                       Explicit opt-out. The script logs that off-host copying is
#                                  switched off, by decision, and exits 0.
#
# UNSET IS AN ERROR, not a default. That is the whole point of this file: a silent no-op would
# reproduce the exact state it was written to end — a stack that looks backed up and is not.
# `none` exists so that switching it off stays possible and stays visible.
#
#   NORA_OFFSITE_RETENTION_DAYS   (default 30) delete copies older than this at the
#                                 destination. 0 disables remote pruning entirely.
#   BACKUP_DIR                    (default /srv/nora/backups) where run-backup.sh writes.
#   NORA_STATE_DIR                (default /srv/nora/state) where the success marker goes.
#
# The systemd unit installed by bootstrap-host.sh reads these from /etc/nora/offsite.env,
# which that script creates with NORA_OFFSITE_TARGET commented out — so the first run fails
# loudly and names the file to edit, instead of succeeding at nothing.
#
# EXIT CODES
#   0  copied (or explicitly disabled with `none`)
#   1  not configured, or a tool/pre-flight problem — nothing was copied
#   2  configured correctly and the COPY FAILED — this is the one that means the off-host leg
#      is broken while everything else looks fine
#
set -euo pipefail

SCRIPT_NAME="$(basename "$0")"

BACKUP_DIR="${BACKUP_DIR:-/srv/nora/backups}"
STATE_DIR="${NORA_STATE_DIR:-/srv/nora/state}"
STATE_FILE="$STATE_DIR/offsite-backup.state"
TARGET="${NORA_OFFSITE_TARGET:-}"
RETENTION_DAYS="${NORA_OFFSITE_RETENTION_DAYS:-30}"

# Same logfmt shape as run-backup.sh, so both legs of the backup story read the same way in
# Loki and the `level=` field keeps driving Loki 3.x's detected_level.
_ts() { date -u '+%Y-%m-%dT%H:%M:%SZ'; }
logf() { local lvl="$1"; shift; printf 'ts=%s level=%s component=offsite-backup %s\n' "$(_ts)" "$lvl" "$*"; }
info() { logf info "$@"; }
warn() { logf warn "$@" >&2; }
error() { logf error "$@" >&2; }
q() { printf '"%s"' "$*"; }

usage() {
  sed -n '2,/^set -euo/p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//; $d'
}

DRY_RUN=0
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1; shift ;;
    --target)  TARGET="${2:?--target requires a value}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) error "event=usage msg=$(q "unknown option: $1")"; usage >&2; exit 1 ;;
  esac
done

# ---------------------------------------------------------------------------
# Configuration gate — the loud failure this file exists to produce
# ---------------------------------------------------------------------------
if [ -z "$TARGET" ]; then
  error "event=config.missing msg=$(q 'NORA_OFFSITE_TARGET is not set, so nothing was copied off this host')"
  error "event=config.help msg=$(q 'set it in /etc/nora/offsite.env — see the header of this script for the three accepted forms')"
  error "event=config.help msg=$(q 'if off-host copying is genuinely not wanted, set NORA_OFFSITE_TARGET=none so the decision is recorded instead of implied')"
  exit 1
fi

if [ "$TARGET" = "none" ]; then
  info "event=disabled msg=$(q 'NORA_OFFSITE_TARGET=none — off-host copying is switched off by decision. Losing this host loses every dump with it.')"
  exit 0
fi

MODE="${TARGET%%:*}"
DEST="${TARGET#*:}"
case "$MODE" in
  rclone|rsync) : ;;
  *)
    error "event=config.invalid target_mode=$(q "$MODE") msg=$(q 'NORA_OFFSITE_TARGET must start with rclone: or rsync: (or be exactly none)')"
    exit 1
    ;;
esac
[ -n "$DEST" ] || { error "event=config.invalid msg=$(q 'NORA_OFFSITE_TARGET has a mode but no destination after it')"; exit 1; }

command -v "$MODE" >/dev/null 2>&1 || {
  error "event=preflight.fail bin=$MODE msg=$(q "$MODE is not installed on this host")"
  case "$MODE" in
    rsync)  error "event=preflight.help msg=$(q 'apt-get install -y rsync')" ;;
    rclone) error "event=preflight.help msg=$(q 'apt-get install -y rclone, then rclone config to create the remote')" ;;
  esac
  exit 1
}

[ -d "$BACKUP_DIR" ] || { error "event=preflight.fail dir=$BACKUP_DIR msg=$(q 'backup directory does not exist — has run-backup.sh ever run?')"; exit 1; }
mkdir -p "$STATE_DIR" 2>/dev/null || warn "event=state.nodir dir=$STATE_DIR msg=$(q 'cannot create the state directory; the success marker will not be written')"

# ---------------------------------------------------------------------------
# What to send: the newest verified dump per database
# ---------------------------------------------------------------------------
# Newest per DATABASE rather than "everything newer than X": the destination keeps its own
# history through this script's retention, and re-sending files it already holds every hour is
# how an off-site copy becomes expensive enough to be switched off.
#
# The database name is the filename prefix that run-backup.sh writes: <db>-<UTC>.dump.
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

mapfile -t databases < <(
  find "$BACKUP_DIR" -maxdepth 1 -type f -name '*.dump' -printf '%f\n' 2>/dev/null |
    sed -n 's/^\(.*\)-[0-9]\{8\}T[0-9]\{6\}Z\.dump$/\1/p' | sort -u
)

if [ "${#databases[@]}" -eq 0 ]; then
  error "event=nothing.to.copy dir=$BACKUP_DIR msg=$(q 'no verified .dump found. A .part is NOT a backup — check the backup service logs.')"
  exit 2
fi

selected=()
for db in "${databases[@]}"; do
  newest="$(find "$BACKUP_DIR" -maxdepth 1 -type f -name "$db-*.dump" | sort | tail -1)"
  [ -n "$newest" ] || continue
  selected+=("$newest")
  for sidecar in "$newest.sha256" "$newest.toc"; do
    [ -f "$sidecar" ] && selected+=("$sidecar")
  done
  info "event=select db=$db file=$(basename "$newest") bytes=$(wc -c < "$newest" | tr -d '[:space:]')"
done

# Hard-link into a staging directory so the transfer sees a fixed, flat set. Hard links, not
# copies: the dumps are large, they are on the same filesystem, and a copy would need as much
# free space as the backup itself on a disk this script exists to stop caring about.
for f in "${selected[@]}"; do
  ln "$f" "$STAGE/$(basename "$f")" 2>/dev/null || cp "$f" "$STAGE/$(basename "$f")"
done

if [ "$DRY_RUN" -eq 1 ]; then
  info "event=dry_run target_mode=$MODE dest=$(q "$DEST") files=${#selected[@]}"
  printf '  %s\n' "${selected[@]}" >&2
  exit 0
fi

# ---------------------------------------------------------------------------
# The transfer
# ---------------------------------------------------------------------------
rc=0
case "$MODE" in
  rclone)
    # `copy`, never `sync`: `sync` makes the destination mirror the source, which means the
    # moment this host loses its dumps — the disaster this copy exists for — the next run
    # would delete them at the destination too. Retention below is what removes old files
    # there, on its own clock.
    info "event=transfer.start tool=rclone dest=$(q "$DEST") files=${#selected[@]}"
    rclone copy "$STAGE" "$DEST" \
      --checksum --transfers 2 --retries 3 --stats-one-line --stats 30s || rc=$?
    ;;
  rsync)
    info "event=transfer.start tool=rsync dest=$(q "$DEST") files=${#selected[@]}"
    # No --delete, for the reason given above. `--checksum` because mtime says nothing useful
    # after a hard link, and a silently truncated dump at the destination is the worst
    # possible outcome of this whole file.
    rsync -a --checksum --partial --human-readable \
      -e 'ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new' \
      "$STAGE"/ "$DEST"/ || rc=$?
    ;;
esac

if [ "$rc" -ne 0 ]; then
  error "event=transfer.fail tool=$MODE rc=$rc msg=$(q 'the off-host copy did NOT happen; the dumps exist only on this machine')"
  exit 2
fi

info "event=transfer.ok tool=$MODE files=${#selected[@]}"

# ---------------------------------------------------------------------------
# Remote retention
# ---------------------------------------------------------------------------
# Only implemented for rclone: `rsync` has no age-based delete, and inventing one out of
# `ssh <host> find -delete` would put a remote `rm` behind a variable this script does not
# validate. For an rsync destination, retention is the destination's problem — say so rather
# than pretend.
if [ "$RETENTION_DAYS" -gt 0 ]; then
  case "$MODE" in
    rclone)
      if rclone delete "$DEST" --min-age "${RETENTION_DAYS}d" --rmdirs 2>/dev/null; then
        info "event=retention.ok tool=rclone older_than_days=$RETENTION_DAYS"
      else
        warn "event=retention.fail tool=rclone msg=$(q 'remote pruning failed; the copies are safe, the destination will grow')"
      fi
      ;;
    rsync)
      info "event=retention.skip tool=rsync msg=$(q 'age-based pruning is not done from here for an rsync destination; configure it where the destination lives')"
      ;;
  esac
fi

# A marker rather than a log line only: `stat -c %Y` on this file answers "when did a copy last
# leave this machine" from a shell, without parsing Loki, which is the question an operator
# asks first when the host has just come back.
if [ -d "$STATE_DIR" ]; then
  {
    printf 'LAST_SUCCESS=%s\n' "$(_ts)"
    printf 'TARGET_MODE=%s\n' "$MODE"
    printf 'FILES=%s\n' "${#selected[@]}"
  } > "$STATE_FILE" 2>/dev/null || warn "event=state.write.fail file=$STATE_FILE"
  chmod 0640 "$STATE_FILE" 2>/dev/null || true
fi

info "event=done msg=$(q "$SCRIPT_NAME finished")"
exit 0
