#!/usr/bin/env bash
# Fails when Portuguese text appears outside the paths where pt-BR is allowed.
#
# The repository is normalised to English (filenames, identifiers, comments, docs,
# log messages, CI). Portuguese survives only in a small, declared set of places —
# the allowlist below. Everything else must be English.
#
# Two detection signals, both deliberately conservative (a missed word costs
# nothing; a false positive costs trust in the check):
#   (a) Portuguese-specific accented characters — high precision;
#   (b) a curated list of Portuguese words that essentially never appear in
#       English source. Words that are also English ("ate", "pro", "com", "as",
#       "no", "os") are excluded on purpose.
# File NAMES are checked with the same two signals.
#
# Exits non-zero listing every `file:line` (or `file: filename`) that violates.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

# ---------------------------------------------------------------------------
# Allowlist — paths where Portuguese is expected. Prefix match against the
# repo-relative path. Every entry states why it is here.
# ---------------------------------------------------------------------------
ALLOWED=(
  # --- 1. pt-BR strings rendered to the end user (the product UI is pt-BR) ---
  "apps/web/src/lib/strings.ts"                 # locale module: the pt-BR UI copy lifted out of components
  "apps/web/src/app/(app)/chat/"                # inline pt-BR UI copy not lifted into strings.ts yet
  "apps/web/src/app/(app)/dashboard/"           # inline pt-BR UI copy not lifted into strings.ts yet
  "apps/web/src/app/(app)/integrations/"        # inline pt-BR UI copy not lifted into strings.ts yet
  "apps/web/src/app/(app)/layout.tsx"           # inline pt-BR UI copy not lifted into strings.ts yet
  "apps/web/src/app/(app)/meetings/"            # inline pt-BR UI copy not lifted into strings.ts yet
  "apps/web/src/app/(app)/settings/"            # inline pt-BR UI copy not lifted into strings.ts yet
  "apps/web/src/app/(app)/tasks/"               # inline pt-BR UI copy not lifted into strings.ts yet
  "apps/web/src/app/(app)/flows/flow-editor.tsx"  # inline pt-BR UI copy not lifted into strings.ts yet
  "apps/web/src/app/(app)/flows/side-panel.tsx"   # inline pt-BR UI copy not lifted into strings.ts yet
  "apps/web/src/app/api/chat/route.ts"          # pt-BR system prompt + UI-facing chat copy
  "apps/web/src/app/auth/"                      # inline pt-BR UI copy not lifted into strings.ts yet
  "apps/web/src/app/error.tsx"                  # inline pt-BR UI copy not lifted into strings.ts yet
  "apps/web/src/app/loading.tsx"                # inline pt-BR UI copy not lifted into strings.ts yet
  "apps/web/src/app/not-found.tsx"              # inline pt-BR UI copy not lifted into strings.ts yet
  "apps/web/src/app/layout.tsx"                 # pt-BR document metadata (title/description)
  "apps/web/src/app/page.tsx"                   # pt-BR landing metadata
  "apps/web/src/components/"                    # inline pt-BR UI copy not lifted into strings.ts yet
  "apps/web/src/lib/api/client.ts"              # pt-BR error copy surfaced directly in the UI
  "apps/web/src/lib/password-policy.ts"         # pt-BR password-rule copy shown in the UI
  "apps/web/src/lib/report/markdown.ts"         # pt-BR headings of the exported meeting report
  "apps/web/src/middleware.ts"                  # pt-BR copy on the auth redirect path
  "apps/admin/src/"                             # operator console UI is pt-BR
  "apps/desktop/src/"                           # desktop product UI is pt-BR
  "apps/desktop/dock.html"                      # desktop product UI is pt-BR
  "apps/desktop/index.html"                     # desktop product UI is pt-BR
  "apps/desktop/overlay.html"                   # desktop product UI is pt-BR
  "apps/desktop/src-tauri/Info.plist"           # macOS permission prompts shown to the user, in pt-BR
  "apps/desktop/src-tauri/src/lib.rs"           # pt-BR tray-menu labels (display text, not identifiers)
  "apps/desktop/src-tauri/src/stt.rs"           # pt-BR speaker label rendered in the transcript UI
  "apps/desktop/src-tauri/gen/schemas/"         # generated by tauri-build; embeds the pt-BR capability description
  # pt-BR execution-log lines rendered in the product's flow-run log (ActionExecutor contract).
  "services/api/src/main/java/br/com/nora/api/infrastructure/integration/actions/"
  "services/api/src/main/java/br/com/nora/api/application/workflow/actions/"

  # --- 2. E-mail templates sent to users ---
  "services/api/src/main/resources/email-templates/"                                    # pt-BR invite e-mail body
  "services/api/src/main/java/br/com/nora/api/application/iam/InviteEmailTemplate.java" # pt-BR invite e-mail copy
  "services/api/src/main/java/br/com/nora/api/infrastructure/email/ResendEmailSender.java" # pt-BR verification / password-reset e-mail bodies

  # --- 3. Seeded demo content and fixtures ---
  "data/"                                                                 # synthetic pt-BR meetings + tenant contexts
  "docs/api/examples/"                                                    # pt-BR sample request/response payloads
  "docs/api/llm-schemas/"                                                 # pt-BR examples inside the LLM JSON Schemas
  "apps/web/src/fixtures/"                                                # pt-BR API response fixtures
  "services/api/src/main/java/br/com/nora/api/application/workflow/WorkflowContextFactory.java" # pt-BR sample analysis for the flow "test run"
  "services/api/src/test/"                                                # pt-BR fixture text inside backend tests
  "services/nlp-worker/tests/"                                            # pt-BR sample transcripts and PII fixtures
  "packages/nlp-baseline/tests/"                                          # pt-BR tokenizer/TF-IDF fixtures
  "apps/desktop/sidecar/tests/"                                           # pt-BR fixture transcripts for the sidecar protocol tests
  "notebooks/"                                                            # academic EDA notebook, pt-BR narrative (FIAP deliverable)

  # --- 4. pt-BR NLP assets ---
  "services/nlp-worker/src/nora_nlp/prompts/"                       # LLM prompt templates — translating them changes model behaviour
  "services/nlp-worker/src/nora_nlp/services/llm_analyzer.py"       # pt-BR prompt fragments concatenated into the prompt at runtime
  "services/nlp-worker/src/nora_nlp/services/live_analyzer.py"      # pt-BR prompt fragment concatenated into the prompt at runtime
  "services/nlp-worker/src/nora_nlp/services/baseline.py"           # cites a pt-BR term as a worked example
  "services/nlp-worker/src/nora_nlp/services/pii_shield.py"         # BR name/honorific lists + pt-BR regex fragments (ADR 0012)
  "services/nlp-worker/src/nora_nlp/services/stub_analyzer.py"      # pt-BR stub analysis output (offline mode)
  "services/nlp-worker/src/nora_nlp/services/stub_live_analyzer.py" # pt-BR stub live highlights (offline mode)
  "services/nlp-worker/src/nora_nlp/services/stub_split_analyzer.py" # pt-BR stub split output (offline mode)
  "services/nlp-worker/CONTEXT.md"                                  # documents the literal pt-BR section headers the prompt makes the LLM emit
  "packages/nlp-baseline/src/nlp_baseline/stopwords.py"             # pt-BR stopword list (ADR 0010)
  "packages/nlp-baseline/src/nlp_baseline/tokenize.py"              # pt-BR tokenizer rules cite pt-BR examples as data
  "packages/nlp-baseline/src/nlp_baseline/tfidf.py"                 # docstring cites a pt-BR accented character as a worked example
  "apps/desktop/src-tauri/src/stt_local.rs"                         # pt-BR Whisper hallucination blocklist (silence artefacts)

  # --- 5. Declared gaps: NOT exemptions. Each one names the change that closes it. ---
  # Applied Flyway migrations are checksum-immutable: editing an applied file makes
  # `flyway:validate` fail against every existing database. The pt-BR COMMENT ON / seed
  # text here can only be replaced by a NEW forward migration, not by editing these.
  "services/api/src/main/resources/db/migration/"
  "services/api/src/main/resources/db/platform/"
  # Documentation PROSE (including the ~76 pt-BR summary/description lines in
  # docs/api/openapi.yaml) is translated by the separate documentation pass that follows
  # this one. THIS pass only renamed doc files, fixed the references and left the prose.
  "docs/"
  # infra/proxmox + the legacy infra/bicep were outside the declared scope of this pass.
  "infra/"
  "GOAL.md"          # PO-authored brief, kept verbatim on purpose
  "README.md"        # pt-BR fragments, closed by the documentation pass
  "SECURITY.md"      # pt-BR fragments, closed by the documentation pass
)

# ---------------------------------------------------------------------------
# Detection
# ---------------------------------------------------------------------------

# Alternation (not a bracket class) so the match is byte-sequence exact and does
# not depend on the locale grep happens to run under.
ACCENTS='á|à|â|ã|é|ê|í|ó|ô|õ|ú|ü|ç|Á|À|Â|Ã|É|Ê|Í|Ó|Ô|Õ|Ú|Ü|Ç'

# Portuguese words that essentially never occur in English source. Kept short on
# purpose. NOT included, because they are also English or common in identifiers:
# ate, pro, com, as, os, no, na, do, da, se, ou, e, a, o, um, ver, tem, sem.
WORDS='nao|sao|voce|entao|tambem|usuario|usuarios|configuracao|configuracoes|arquivo|arquivos|senha|senhas|reuniao|reunioes|transcricao|transcricoes|integracao|integracoes|atualizacao|mensagem|mensagens|para|que|uma|isso|esse|essa|pra|nenhum|nenhuma|servico|servicos|qualquer|porque|quando|porem|embora|apenas|ainda|agora|depois|antes|sobre|durante|atraves|muito|tudo'

violations=0

is_allowed() {
  local path=$1 entry
  for entry in "${ALLOWED[@]}"; do
    case "$path" in
      "$entry"*) return 0 ;;
    esac
  done
  return 1
}

# Build the candidate list once: every tracked file that is not allowlisted.
# The content scan below then runs grep TWICE IN TOTAL over that list, not twice
# per file — two process substitutions per file would open ~1400 descriptors on a
# repo this size and abort the run partway through, which under-reports silently.
candidates=()
while IFS= read -r file; do
  is_allowed "$file" && continue

  # Filenames and directory names must be English too.
  if printf '%s\n' "$file" | grep -qE "($ACCENTS)"; then
    printf '%s: Portuguese character in the file name\n' "$file"
    violations=$((violations + 1))
  elif printf '%s\n' "$file" | grep -qiE "(^|[^a-z])($WORDS)([^a-z]|$)"; then
    printf '%s: Portuguese word in the file name\n' "$file"
    violations=$((violations + 1))
  fi

  [ -f "$file" ] && candidates+=("$file")
done < <(git ls-files)

if [ "${#candidates[@]}" -gt 0 ]; then
  # `-I` skips binary files (fonts, icons, lockfile blobs). `-H` forces the
  # filename prefix even when a single file is left after allowlisting.
  findings=$(
    {
      printf '%s\0' "${candidates[@]}" |
        xargs -0 grep -nIHE "($ACCENTS)" -- 2>/dev/null |
        cut -d: -f1,2 | sed 's/$/: Portuguese character/' || true
      printf '%s\0' "${candidates[@]}" |
        xargs -0 grep -nIHiE "\b($WORDS)\b" -- 2>/dev/null |
        cut -d: -f1,2 | sed 's/$/: Portuguese word/' || true
    } | sort -u
  )

  if [ -n "$findings" ]; then
    printf '%s\n' "$findings"
    violations=$((violations + $(printf '%s\n' "$findings" | wc -l)))
  fi
fi

if [ "$violations" -gt 0 ]; then
  printf '\n%d Portuguese finding(s) outside the allowlist in scripts/check-language.sh.\n' "$violations" >&2
  printf 'Either translate the text, or add the path to the allowlist with an honest reason.\n' >&2
  exit 1
fi

printf 'OK — no Portuguese found outside the declared allowlist.\n'
