"""Live Analyzer: real-time analysis of partial meeting chunks.

Pipeline (similar to llm_analyzer.py, but lighter):
  1. Loads the versioned prompt ``live-highlights-v1.md``.
  2. Injects chunk + previous highlights (for dedup) into the template.
  3. Calls the LLM with structured output (strict JSON Schema).
  4. On strict failure, falls back to JSON mode.
  5. Validates the response with Pydantic (``LiveHighlightsV1``).
  6. Returns ``LiveAnalyzeResponse`` with execution metadata.

Provider configured via ``LLM_BASE_URL`` / ``LLM_API_KEY`` / ``LLM_MODEL``
(ADR 0004). Default: OpenAI direct with ``gpt-4o-mini``.
"""

from __future__ import annotations

import json
import logging
import time

from ..clients.llm import LlmClient
from ..models import LiveAnalyzeRequest, LiveAnalyzeResponse, LiveHighlightsV1
from ..settings import Settings
from ..time_budget import LlmBudgetExceededError, TimeBudget
from .prompt_utils import load_prompt, render_template
from .shield_walk import shield_tree

logger = logging.getLogger(__name__)


def _redact_highlights_dict(data: dict) -> tuple[dict, int]:
    """Applies PII Shield to every free-text field of `data`.

    `previous_highlights` comes from the client (backend forwards it, but the
    original content was generated by the previous round's LLM — it may contain
    PII that escaped the first shield, especially in fields like `sourceQuote`
    that echo the transcript). Re-applying the shield here avoids amplification
    on each iteration. ADR 0012.

    This used to walk a hand-kept `{collection: (field, ...)}` dictionary, which named every
    text field of `LiveHighlightsV1` correctly on the day it was written and could not stay
    correct: a text field added to `LiveHighlightItem` or `LiveTaskItem` afterwards would stop
    reaching the shield with nothing failing, and `piiRedactionsApplied` would keep reporting a
    clean audit trail for text nobody inspected. `shield_tree` is the same argument the analysis
    path already made, applied to the endpoint with the higher amplification -- this structure
    is re-injected into the prompt on every round.

    Non-string leaves (`confidence`, `priority`) are returned untouched by the walk, so nothing
    is redacted here that the field list did not already cover.
    """
    counter = [0]
    # Per top-level value rather than one call on `data`, only so the result is a `dict` by
    # construction instead of by narrowing an `object` the walk is typed to return.
    return {key: shield_tree(value, counter) for key, value in data.items()}, counter[0]


def _build_previous_highlights_section(
    previous: LiveHighlightsV1 | None,
) -> tuple[str, int]:
    if previous is None:
        return "", 0
    data, extra = _redact_highlights_dict(previous.model_dump(by_alias=True))
    has_any = any(data.get(k) for k in ("decisions", "nextSteps", "observations", "tasks"))
    if not has_any:
        return "", extra
    section = (
        "Destaques ja identificados anteriormente (NAO duplique):\n"
        "```json\n"
        f"{json.dumps(data, ensure_ascii=False, indent=2)}\n"
        "```\n"
    )
    return section, extra


def _build_json_schema_for_live() -> dict:
    return {
        "type": "object",
        "properties": {
            "decisions": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "text": {"type": "string"},
                        "confidence": {"type": "number"},
                        "sourceQuote": {"type": "string"},
                    },
                    "required": ["text", "confidence", "sourceQuote"],
                    "additionalProperties": False,
                },
            },
            "nextSteps": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "text": {"type": "string"},
                        "confidence": {"type": "number"},
                        "sourceQuote": {"type": "string"},
                    },
                    "required": ["text", "confidence", "sourceQuote"],
                    "additionalProperties": False,
                },
            },
            "observations": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "text": {"type": "string"},
                        "confidence": {"type": "number"},
                        "sourceQuote": {"type": "string"},
                    },
                    "required": ["text", "confidence", "sourceQuote"],
                    "additionalProperties": False,
                },
            },
            "tasks": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "title": {"type": "string"},
                        "assignee": {"type": ["string", "null"]},
                        "priority": {
                            "type": "string",
                            "enum": ["LOW", "MEDIUM", "HIGH"],
                        },
                        "sourceQuote": {"type": "string"},
                    },
                    "required": ["title", "assignee", "priority", "sourceQuote"],
                    "additionalProperties": False,
                },
            },
        },
        "required": ["decisions", "nextSteps", "observations", "tasks"],
        "additionalProperties": False,
    }


def analyze(
    req: LiveAnalyzeRequest,
    settings: Settings,
    *,
    pii_redactions_applied: int = 0,
    budget: TimeBudget | None = None,
) -> LiveAnalyzeResponse:
    started = time.monotonic()

    # Same request budget as the other two analyzers (`time_budget.py`), and the one that most
    # deserves it: a live chunk is answered while the meeting is still happening, so an answer
    # that arrives after the caller gave up is worth even less here than on `/analyze`.
    budget = budget or TimeBudget.from_settings(settings)

    client = LlmClient(settings, budget=budget)

    system_prompt, user_template = load_prompt("live-highlights-v1")

    previous_section, prev_redactions = _build_previous_highlights_section(req.previous_highlights)
    pii_redactions_applied = pii_redactions_applied + prev_redactions

    user_prompt = render_template(
        user_template,
        language=req.language,
        transcript_chunk=req.transcript_chunk,
        previous_highlights_section=previous_section,
    )

    json_schema = _build_json_schema_for_live()

    try:
        raw_json, tokens_in, tokens_out = client.chat_structured(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            json_schema=json_schema,
            schema_name="live_highlights",
            temperature=0.1,
            max_tokens=2048,
        )
    except LlmBudgetExceededError:
        # Ahead of the generic branch on purpose: see the same clause in `llm_analyzer.analyze`.
        raise
    except Exception as exc:
        logger.warning("Structured output failed in live, falling back to JSON mode: %s", exc)
        raw_json, tokens_in, tokens_out = client.chat_json(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            temperature=0.1,
            max_tokens=2048,
        )

    # Do NOT log raw_json: ADR 0012 (PII never logged).
    logger.debug("Live LLM raw response: %d chars", len(raw_json))

    parsed = json.loads(raw_json)
    highlights = LiveHighlightsV1.model_validate(parsed)

    elapsed_ms = int((time.monotonic() - started) * 1000)

    return LiveAnalyzeResponse.model_validate(
        {
            **highlights.model_dump(by_alias=True),
            "metadata": {
                "processingMillis": elapsed_ms,
                "tokensInput": tokens_in,
                "tokensOutput": tokens_out,
                "piiRedactionsApplied": pii_redactions_applied,
                "modelVersion": f"{settings.llm_provider}-{settings.llm_model}",
            },
        }
    )
