"""Live Analyzer: real-time analysis of partial meeting chunks.

Pipeline (similar to llm_analyzer.py, but lighter):
  1. Loads the versioned prompt ``live-highlights-v1.md``.
  2. Injects chunk + previous highlights (for dedup) into the template.
  3. Calls the LLM with structured output (strict JSON Schema).
  4. On strict failure, falls back to JSON mode.
  5. Validates the response with Pydantic (``LiveHighlightsV1``).
  6. Returns ``LiveAnalyzeResponse`` with execution metadata.

Provider configured via ``LLM_BASE_URL`` / ``LLM_API_KEY`` / ``LLM_MODEL``
(ADR 0004). Default: OpenAI direct with ``gpt-4o-mini``.
"""

from __future__ import annotations

import json
import logging
import time

from ..clients.llm import LlmClient
from ..models import LiveAnalyzeRequest, LiveAnalyzeResponse, LiveHighlightsV1
from ..settings import Settings
from .pii_shield import redact as pii_redact
from .prompt_utils import load_prompt, render_template

logger = logging.getLogger(__name__)


_TEXT_FIELDS_HIGHLIGHTS = {
    "decisions": ("text", "sourceQuote"),
    "nextSteps": ("text", "sourceQuote"),
    "observations": ("text", "sourceQuote"),
    "tasks": ("title", "assignee", "sourceQuote"),
}


def _redact_highlights_dict(data: dict) -> tuple[dict, int]:
    """Applies PII Shield to every free-text field of `data`.

    `previous_highlights` comes from the client (backend forwards it, but the
    original content was generated by the previous round's LLM — it may contain
    PII that escaped the first shield, especially in fields like `sourceQuote`
    that echo the transcript). Re-applying the shield here avoids amplification
    on each iteration. ADR 0012.
    """
    extra_redactions = 0
    for collection_key, text_fields in _TEXT_FIELDS_HIGHLIGHTS.items():
        items = data.get(collection_key) or []
        for item in items:
            for field in text_fields:
                value = item.get(field)
                if isinstance(value, str) and value:
                    result = pii_redact(value)
                    if result.redactions:
                        item[field] = result.redacted_text
                        extra_redactions += len(result.redactions)
    return data, extra_redactions


def _build_previous_highlights_section(
    previous: LiveHighlightsV1 | None,
) -> tuple[str, int]:
    if previous is None:
        return "", 0
    data = previous.model_dump(by_alias=True)
    data, extra = _redact_highlights_dict(data)
    has_any = any(data.get(k) for k in ("decisions", "nextSteps", "observations", "tasks"))
    if not has_any:
        return "", extra
    section = (
        "Destaques ja identificados anteriormente (NAO duplique):\n"
        "```json\n"
        f"{json.dumps(data, ensure_ascii=False, indent=2)}\n"
        "```\n"
    )
    return section, extra


def _build_json_schema_for_live() -> dict:
    return {
        "type": "object",
        "properties": {
            "decisions": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "text": {"type": "string"},
                        "confidence": {"type": "number"},
                        "sourceQuote": {"type": "string"},
                    },
                    "required": ["text", "confidence", "sourceQuote"],
                    "additionalProperties": False,
                },
            },
            "nextSteps": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "text": {"type": "string"},
                        "confidence": {"type": "number"},
                        "sourceQuote": {"type": "string"},
                    },
                    "required": ["text", "confidence", "sourceQuote"],
                    "additionalProperties": False,
                },
            },
            "observations": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "text": {"type": "string"},
                        "confidence": {"type": "number"},
                        "sourceQuote": {"type": "string"},
                    },
                    "required": ["text", "confidence", "sourceQuote"],
                    "additionalProperties": False,
                },
            },
            "tasks": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "title": {"type": "string"},
                        "assignee": {"type": ["string", "null"]},
                        "priority": {
                            "type": "string",
                            "enum": ["LOW", "MEDIUM", "HIGH"],
                        },
                        "sourceQuote": {"type": "string"},
                    },
                    "required": ["title", "assignee", "priority", "sourceQuote"],
                    "additionalProperties": False,
                },
            },
        },
        "required": ["decisions", "nextSteps", "observations", "tasks"],
        "additionalProperties": False,
    }


def analyze(
    req: LiveAnalyzeRequest,
    settings: Settings,
    *,
    pii_redactions_applied: int = 0,
) -> LiveAnalyzeResponse:
    started = time.monotonic()

    client = LlmClient(settings)

    system_prompt, user_template = load_prompt("live-highlights-v1")

    previous_section, prev_redactions = _build_previous_highlights_section(req.previous_highlights)
    pii_redactions_applied = pii_redactions_applied + prev_redactions

    user_prompt = render_template(
        user_template,
        language=req.language,
        transcript_chunk=req.transcript_chunk,
        previous_highlights_section=previous_section,
    )

    json_schema = _build_json_schema_for_live()

    try:
        raw_json, tokens_in, tokens_out = client.chat_structured(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            json_schema=json_schema,
            schema_name="live_highlights",
            temperature=0.1,
            max_tokens=2048,
        )
    except Exception as exc:
        logger.warning("Structured output falhou no live, tentando JSON mode fallback: %s", exc)
        raw_json, tokens_in, tokens_out = client.chat_json(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            temperature=0.1,
            max_tokens=2048,
        )

    # Do NOT log raw_json: ADR 0012 (PII never logged).
    logger.debug("Live LLM raw response: %d chars", len(raw_json))

    parsed = json.loads(raw_json)
    highlights = LiveHighlightsV1.model_validate(parsed)

    elapsed_ms = int((time.monotonic() - started) * 1000)

    return LiveAnalyzeResponse.model_validate(
        {
            **highlights.model_dump(by_alias=True),
            "metadata": {
                "processingMillis": elapsed_ms,
                "tokensInput": tokens_in,
                "tokensOutput": tokens_out,
                "piiRedactionsApplied": pii_redactions_applied,
                "modelVersion": f"{settings.llm_provider}-{settings.llm_model}",
            },
        }
    )
