-- V017: Customer Confidence persistence foundation (ADR 0015).
--
-- Persists customer accounts (customer_accounts), the meeting<->account link
-- (meeting_account_links) and the customer confidence assessment generated by the worker
-- (customer_confidence_assessments + customer_buying_signals + customer_objections).
--
-- SCOPE: the persistence foundation only. NO wiring into the analysis pipeline
-- yet (AnalysisService does not write here). The worker does NOT emit the
-- customerConfidence block yet; this schema is the target contract (see meeting-analysis-v1.schema.json).
--
-- Rules:
--   - Every tenant-bound table carries an explicit tenant_id (ADR 0002).
--   - Cascade ON DELETE on meeting_id/tenant_id/assessment_id guarantees cleanup.
--   - 1-1 between (meeting, account) and customer_confidence_assessments (composite UNIQUE):
--     a meeting can touch more than one account, but at most one assessment per pair.
--   - Enums mirror the customerConfidence block of meeting-analysis-v1.schema.json.
--   - RLS (V016) enabled on the 3 tenant-owned tables; children (signals/objections)
--     inherit isolation via the assessment_id cascade (no policy of their own, same as coverage).

-- ============================================================
-- Customer account (lead/account). Get-or-create dedup by (tenant, LOWER(name)).
-- ============================================================
CREATE TABLE customer_accounts (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id      UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name           TEXT NOT NULL,
    owner_user_id  UUID REFERENCES users(id) ON DELETE SET NULL,
    stage          TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_customer_accounts_tenant ON customer_accounts (tenant_id);
CREATE UNIQUE INDEX idx_customer_accounts_tenant_name
    ON customer_accounts (tenant_id, LOWER(name));

-- ============================================================
-- N:N link meeting <-> account.
-- ============================================================
CREATE TABLE meeting_account_links (
    meeting_id           UUID NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
    customer_account_id  UUID NOT NULL REFERENCES customer_accounts(id) ON DELETE CASCADE,
    tenant_id            UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,

    PRIMARY KEY (meeting_id, customer_account_id)
);

CREATE INDEX idx_meeting_account_links_tenant ON meeting_account_links (tenant_id);
CREATE INDEX idx_meeting_account_links_account
    ON meeting_account_links (customer_account_id);

-- ============================================================
-- Customer confidence assessment generated by the worker.
-- 1-1 per (meeting, account): composite UNIQUE (meeting_id, customer_account_id).
-- ============================================================
CREATE TABLE customer_confidence_assessments (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id            UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    meeting_id           UUID NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
    customer_account_id  UUID NOT NULL REFERENCES customer_accounts(id) ON DELETE CASCADE,
    score                INTEGER NOT NULL,
    band                 VARCHAR(10) NOT NULL,
    trend                VARCHAR(10),
    rationale            TEXT NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT customer_confidence_score_chk CHECK (score BETWEEN 0 AND 100),
    CONSTRAINT customer_confidence_band_chk  CHECK (band IN ('LOW','MEDIUM','HIGH')),
    CONSTRAINT customer_confidence_trend_chk
        CHECK (trend IS NULL OR trend IN ('IMPROVING','STABLE','DECLINING')),
    CONSTRAINT customer_confidence_meeting_account_uk UNIQUE (meeting_id, customer_account_id)
);

CREATE INDEX idx_customer_confidence_tenant ON customer_confidence_assessments (tenant_id);

-- ============================================================
-- Buying signals detected (list ordered by position). Child of the assessment.
-- ============================================================
CREATE TABLE customer_buying_signals (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    assessment_id  UUID NOT NULL REFERENCES customer_confidence_assessments(id) ON DELETE CASCADE,
    type           VARCHAR(30) NOT NULL,
    quote          TEXT NOT NULL,
    weight         NUMERIC(4,3),
    position       INTEGER NOT NULL,

    CONSTRAINT customer_buying_signals_type_chk
        CHECK (type IN ('BUDGET_DISCUSSED','TIMELINE_DISCUSSED','STAKEHOLDER_INVOLVED',
                        'NEXT_STEP_REQUESTED','REFERENCE_REQUESTED','PROPOSAL_REQUESTED','OTHER')),
    CONSTRAINT customer_buying_signals_weight_chk
        CHECK (weight IS NULL OR (weight >= 0 AND weight <= 1)),
    CONSTRAINT customer_buying_signals_position_chk CHECK (position >= 0)
);

CREATE INDEX idx_customer_buying_signals_assessment
    ON customer_buying_signals (assessment_id);

-- ============================================================
-- Objections raised (list ordered by position). Child of the assessment.
-- ============================================================
CREATE TABLE customer_objections (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    assessment_id  UUID NOT NULL REFERENCES customer_confidence_assessments(id) ON DELETE CASCADE,
    type           VARCHAR(30) NOT NULL,
    quote          TEXT NOT NULL,
    severity       VARCHAR(10) NOT NULL,
    competitor     TEXT,
    position       INTEGER NOT NULL,

    CONSTRAINT customer_objections_type_chk
        CHECK (type IN ('PRICE','TIMELINE','AUTHORITY','NEED','COMPETITOR_MENTION',
                        'TRUST','FEATURE_GAP','OTHER')),
    CONSTRAINT customer_objections_severity_chk CHECK (severity IN ('LOW','MEDIUM','HIGH')),
    CONSTRAINT customer_objections_position_chk CHECK (position >= 0)
);

CREATE INDEX idx_customer_objections_assessment ON customer_objections (assessment_id);

-- ============================================================
-- RLS (ADR 0002, follows V016) — tenant-owned tables only.
-- customer_buying_signals and customer_objections get NO policy: they are direct
-- children of the assessment (cascade via assessment_id), same as meeting_outcome_coverage.
-- ============================================================
ALTER TABLE customer_accounts ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON customer_accounts
    USING (tenant_id = nora.current_tenant_id())
    WITH CHECK (tenant_id = nora.current_tenant_id());

ALTER TABLE meeting_account_links ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON meeting_account_links
    USING (tenant_id = nora.current_tenant_id())
    WITH CHECK (tenant_id = nora.current_tenant_id());

ALTER TABLE customer_confidence_assessments ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON customer_confidence_assessments
    USING (tenant_id = nora.current_tenant_id())
    WITH CHECK (tenant_id = nora.current_tenant_id());
